ERROR - 2020-12-29 00:01:05 --> mysqli_sql_exception: Column 'estate_type_id' cannot be null in C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `of...')
#1 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `of...')
#2 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `of...')
#3 C:\xampp\htdocs\Riyadh\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `of...', Array, false)
#4 C:\xampp\htdocs\Riyadh\app\Models\User_model.php(325): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(173): App\Models\User_model->add_offer('19', '2020-12-29 12:0...', 'cup.png', 'asdf', 'asdf', 'Check', 'null', 'asdf', 'asdf', NULL)
#6 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->upload()
#7 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2020-12-29 00:08:02 --> mysqli_sql_exception: Column 'estate_type_id' cannot be null in C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `of...')
#1 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `of...')
#2 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `of...')
#3 C:\xampp\htdocs\Riyadh\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `of...', Array, false)
#4 C:\xampp\htdocs\Riyadh\app\Models\User_model.php(355): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(204): App\Models\User_model->edit_add_offer('19', '2020-12-29 12:0...', 'background777.j...', 'asdf', 'asdf', 'Check', 'null', 'asdf', 'asdf', NULL)
#6 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->edit_upload()
#7 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2020-12-29 00:08:42 --> mysqli_sql_exception: Column 'estate_type_id' cannot be null in C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `of...')
#1 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `of...')
#2 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `of...')
#3 C:\xampp\htdocs\Riyadh\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `of...', Array, false)
#4 C:\xampp\htdocs\Riyadh\app\Models\User_model.php(355): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(204): App\Models\User_model->edit_add_offer('19', '2020-12-29 12:0...', 'background777.j...', 'asdf', 'asdf', 'Check', 'null', 'asdf', 'asdf', NULL)
#6 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->edit_upload()
#7 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2020-12-29 00:09:04 --> mysqli_sql_exception: Column 'estate_type_id' cannot be null in C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `of...')
#1 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `of...')
#2 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `of...')
#3 C:\xampp\htdocs\Riyadh\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `of...', Array, false)
#4 C:\xampp\htdocs\Riyadh\app\Models\User_model.php(355): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(204): App\Models\User_model->edit_add_offer('19', '2020-12-29 12:0...', 'background777.j...', 'asdf', 'asdf', 'Check', 'null', 'asdf', 'asdf', NULL)
#6 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->edit_upload()
#7 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2020-12-29 00:09:35 --> mysqli_sql_exception: Column 'location' cannot be null in C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `of...')
#1 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `of...')
#2 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `of...')
#3 C:\xampp\htdocs\Riyadh\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `of...', Array, false)
#4 C:\xampp\htdocs\Riyadh\app\Models\User_model.php(355): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(204): App\Models\User_model->edit_add_offer('19', '2020-12-29 12:0...', 'background777.j...', 'asdf', 'asdf', 'Check', 'test', 'asdf', 'asdf', NULL)
#6 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->edit_upload()
#7 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2020-12-29 00:11:52 --> mysqli_sql_exception: Column 'location' cannot be null in C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `of...')
#1 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `of...')
#2 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `of...')
#3 C:\xampp\htdocs\Riyadh\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `of...', Array, false)
#4 C:\xampp\htdocs\Riyadh\app\Models\User_model.php(356): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(204): App\Models\User_model->edit_add_offer('19', '2020-12-29 12:1...', 'background777.j...', 'asdf', 'asdf', 'Check', 'test', 'asdf', 'asdf', NULL)
#6 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->edit_upload()
#7 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2020-12-29 00:20:47 --> mysqli_sql_exception: Column 'img_url_id' cannot be null in C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `of...')
#1 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `of...')
#2 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `of...')
#3 C:\xampp\htdocs\Riyadh\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `of...', Array, false)
#4 C:\xampp\htdocs\Riyadh\app\Models\User_model.php(355): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(204): App\Models\User_model->edit_add_offer('19', '2020-12-29 12:2...', 'background666.j...', 'asdf', 'asdf', 'Check', 'asdfwef', 'asdf', 'asdf', 'asdf')
#6 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->edit_upload()
#7 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2020-12-29 00:24:22 --> mysqli_sql_exception: Column 'img_url_id' cannot be null in C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php(314): mysqli->query('REPLACE INTO `o...')
#1 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('REPLACE INTO `o...')
#2 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('REPLACE INTO `o...')
#3 C:\xampp\htdocs\Riyadh\system\Database\BaseBuilder.php(2358): CodeIgniter\Database\BaseConnection->query('REPLACE INTO `o...', Array, false)
#4 C:\xampp\htdocs\Riyadh\app\Models\User_model.php(357): CodeIgniter\Database\BaseBuilder->replace(Array)
#5 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(205): App\Models\User_model->edit_add_offer(NULL, '19', '2020-12-29 12:2...', 'background666.j...', 'asdf', 'asdf', 'Check', 'asdfwef', 'asdf', 'asdf', 'asdf')
#6 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->edit_upload()
#7 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2020-12-29 00:24:46 --> mysqli_sql_exception: Column 'img_url_id' cannot be null in C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php(314): mysqli->query('REPLACE INTO `o...')
#1 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('REPLACE INTO `o...')
#2 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('REPLACE INTO `o...')
#3 C:\xampp\htdocs\Riyadh\system\Database\BaseBuilder.php(2358): CodeIgniter\Database\BaseConnection->query('REPLACE INTO `o...', Array, false)
#4 C:\xampp\htdocs\Riyadh\app\Models\User_model.php(357): CodeIgniter\Database\BaseBuilder->replace(Array)
#5 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(205): App\Models\User_model->edit_add_offer(NULL, '19', '2020-12-29 12:2...', 'background666.j...', 'testasdf', 'testasdf', 'Check', 'test', 'testasdf', 'test', 'test')
#6 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->edit_upload()
#7 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2020-12-29 00:24:46 --> mysqli_sql_exception: Column 'img_url_id' cannot be null in C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php(314): mysqli->query('REPLACE INTO `o...')
#1 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('REPLACE INTO `o...')
#2 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('REPLACE INTO `o...')
#3 C:\xampp\htdocs\Riyadh\system\Database\BaseBuilder.php(2358): CodeIgniter\Database\BaseConnection->query('REPLACE INTO `o...', Array, false)
#4 C:\xampp\htdocs\Riyadh\app\Models\User_model.php(357): CodeIgniter\Database\BaseBuilder->replace(Array)
#5 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(205): App\Models\User_model->edit_add_offer(NULL, '19', '2020-12-29 12:2...', 'background666.j...', 'testasdf', 'testasdf', 'Check', 'test', 'testasdf', 'test', 'test')
#6 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->edit_upload()
#7 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2020-12-29 00:29:12 --> mysqli_sql_exception: Column 'estate_type_id' cannot be null in C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php(314): mysqli->query('REPLACE INTO `o...')
#1 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('REPLACE INTO `o...')
#2 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('REPLACE INTO `o...')
#3 C:\xampp\htdocs\Riyadh\system\Database\BaseBuilder.php(2358): CodeIgniter\Database\BaseConnection->query('REPLACE INTO `o...', Array, false)
#4 C:\xampp\htdocs\Riyadh\app\Models\User_model.php(358): CodeIgniter\Database\BaseBuilder->replace(Array)
#5 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(205): App\Models\User_model->edit_add_offer('4', '19', '2020-12-29 12:2...', 'background555.j...', 'asdfasdfasdfasd...', 'asdf', 'Check', 'null', 'asdf', 'asdf', 'asdfadsf')
#6 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->edit_upload()
#7 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2020-12-29 00:29:12 --> mysqli_sql_exception: Column 'estate_type_id' cannot be null in C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php(314): mysqli->query('REPLACE INTO `o...')
#1 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('REPLACE INTO `o...')
#2 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('REPLACE INTO `o...')
#3 C:\xampp\htdocs\Riyadh\system\Database\BaseBuilder.php(2358): CodeIgniter\Database\BaseConnection->query('REPLACE INTO `o...', Array, false)
#4 C:\xampp\htdocs\Riyadh\app\Models\User_model.php(358): CodeIgniter\Database\BaseBuilder->replace(Array)
#5 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(205): App\Models\User_model->edit_add_offer('1', '19', '2020-12-29 12:2...', 'background555.j...', 'asdfasdfasdfasd...', 'asdf', 'Check', 'null', 'asdf', 'asdf', 'asdfadsf')
#6 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->edit_upload()
#7 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2020-12-29 00:30:10 --> mysqli_sql_exception: Column 'estate_type_id' cannot be null in C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php(314): mysqli->query('REPLACE INTO `o...')
#1 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('REPLACE INTO `o...')
#2 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('REPLACE INTO `o...')
#3 C:\xampp\htdocs\Riyadh\system\Database\BaseBuilder.php(2358): CodeIgniter\Database\BaseConnection->query('REPLACE INTO `o...', Array, false)
#4 C:\xampp\htdocs\Riyadh\app\Models\User_model.php(357): CodeIgniter\Database\BaseBuilder->replace(Array)
#5 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(205): App\Models\User_model->edit_add_offer('1', '19', '2020-12-29 12:3...', 'background555.j...', 'asdfasdfasdfasd...', 'asdf', 'Check', 'null', 'asdf', 'asdf', 'asdfadsf')
#6 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->edit_upload()
#7 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2020-12-29 00:30:10 --> mysqli_sql_exception: Column 'estate_type_id' cannot be null in C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php(314): mysqli->query('REPLACE INTO `o...')
#1 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('REPLACE INTO `o...')
#2 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('REPLACE INTO `o...')
#3 C:\xampp\htdocs\Riyadh\system\Database\BaseBuilder.php(2358): CodeIgniter\Database\BaseConnection->query('REPLACE INTO `o...', Array, false)
#4 C:\xampp\htdocs\Riyadh\app\Models\User_model.php(357): CodeIgniter\Database\BaseBuilder->replace(Array)
#5 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(205): App\Models\User_model->edit_add_offer('4', '19', '2020-12-29 12:3...', 'background555.j...', 'asdfasdfasdfasd...', 'asdf', 'Check', 'null', 'asdf', 'asdf', 'asdfadsf')
#6 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->edit_upload()
#7 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2020-12-29 00:32:22 --> mysqli_sql_exception: Column 'district_id' cannot be null in C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `of...')
#1 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `of...')
#2 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `of...')
#3 C:\xampp\htdocs\Riyadh\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `of...', Array, false)
#4 C:\xampp\htdocs\Riyadh\app\Models\User_model.php(325): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(173): App\Models\User_model->add_offer('34', '2020-12-29 12:3...', 'background.jpg', 'asdfasdf', 'asdfasdfafdsasd...', 'asdfwegasd', 'asdfasdfasdfads...', 'asdf', 'asdf', 'asdf')
#6 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->upload()
#7 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2020-12-29 00:32:47 --> mysqli_sql_exception: Column 'district_id' cannot be null in C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `of...')
#1 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `of...')
#2 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `of...')
#3 C:\xampp\htdocs\Riyadh\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `of...', Array, false)
#4 C:\xampp\htdocs\Riyadh\app\Models\User_model.php(325): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(173): App\Models\User_model->add_offer('34', '2020-12-29 12:3...', 'background.jpg', 'asdfasdf', 'asdfasdfafdsasd...', 'asdfwegasd', 'asdfasdfasdfads...', 'asdf', 'asdf', 'asdf')
#6 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->upload()
#7 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2020-12-29 00:37:09 --> mysqli_sql_exception: Column 'district_id' cannot be null in C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `of...')
#1 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `of...')
#2 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `of...')
#3 C:\xampp\htdocs\Riyadh\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `of...', Array, false)
#4 C:\xampp\htdocs\Riyadh\app\Models\User_model.php(325): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(173): App\Models\User_model->add_offer('34', '2020-12-29 12:3...', 'background888.j...', 'alrosya', '1234', 'Check', 'asdfwef', '12341243', 'asdf', 'qwef')
#6 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->upload()
#7 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2020-12-29 00:40:24 --> mysqli_sql_exception: Column 'district_id' cannot be null in C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `of...')
#1 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `of...')
#2 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `of...')
#3 C:\xampp\htdocs\Riyadh\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `of...', Array, false)
#4 C:\xampp\htdocs\Riyadh\app\Models\User_model.php(325): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(173): App\Models\User_model->add_offer('34', '2020-12-29 12:4...', 'background888.j...', 'alrosya', '1234', 'Check', 'asdfwef', '12341243', 'asdf', 'qwef')
#6 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->upload()
#7 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2020-12-29 01:32:36 --> mysqli_sql_exception: Column 'district' cannot be null in C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php(314): mysqli->query('REPLACE INTO `d...')
#1 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('REPLACE INTO `d...')
#2 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('REPLACE INTO `d...')
#3 C:\xampp\htdocs\Riyadh\system\Database\BaseBuilder.php(2358): CodeIgniter\Database\BaseConnection->query('REPLACE INTO `d...', Array, false)
#4 C:\xampp\htdocs\Riyadh\app\Models\User_model.php(244): CodeIgniter\Database\BaseBuilder->replace(Array)
#5 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(123): App\Models\User_model->change_district('2', NULL, '1')
#6 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->change_district()
#7 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2020-12-29 07:17:48 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'and c.id = a.estate_type_id
            LEFT JOIN photo AS d on and d.id = a...' at line 3 in C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT a.billbo...')
#1 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('SELECT a.billbo...')
#2 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT a.billbo...')
#3 C:\xampp\htdocs\Riyadh\app\Models\User_model.php(411): CodeIgniter\Database\BaseConnection->query('SELECT a.billbo...')
#4 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(231): App\Models\User_model->post_data_edit('3', '1')
#5 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->post_data_edit()
#6 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2020-12-29 07:17:50 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'and c.id = a.estate_type_id
            LEFT JOIN photo AS d on and d.id = a...' at line 3 in C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT a.billbo...')
#1 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('SELECT a.billbo...')
#2 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT a.billbo...')
#3 C:\xampp\htdocs\Riyadh\app\Models\User_model.php(411): CodeIgniter\Database\BaseConnection->query('SELECT a.billbo...')
#4 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(231): App\Models\User_model->post_data_edit('3', '1')
#5 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->post_data_edit()
#6 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2020-12-29 07:18:12 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'and c.id = a.estate_type_id
            LEFT JOIN photo AS d on and d.id = a...' at line 3 in C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT a.billbo...')
#1 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('SELECT a.billbo...')
#2 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT a.billbo...')
#3 C:\xampp\htdocs\Riyadh\app\Models\User_model.php(411): CodeIgniter\Database\BaseConnection->query('SELECT a.billbo...')
#4 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(231): App\Models\User_model->post_data_edit('6', '1')
#5 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->post_data_edit()
#6 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2020-12-29 07:18:14 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'and c.id = a.estate_type_id
            LEFT JOIN photo AS d on and d.id = a...' at line 3 in C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT a.billbo...')
#1 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('SELECT a.billbo...')
#2 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT a.billbo...')
#3 C:\xampp\htdocs\Riyadh\app\Models\User_model.php(411): CodeIgniter\Database\BaseConnection->query('SELECT a.billbo...')
#4 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(231): App\Models\User_model->post_data_edit('4', '1')
#5 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->post_data_edit()
#6 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2020-12-29 07:19:43 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'and d.id = a.img_url_id
            WHERE a.id = '3'' at line 4 in C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT a.billbo...')
#1 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('SELECT a.billbo...')
#2 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT a.billbo...')
#3 C:\xampp\htdocs\Riyadh\app\Models\User_model.php(411): CodeIgniter\Database\BaseConnection->query('SELECT a.billbo...')
#4 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(231): App\Models\User_model->post_data_edit('3', '1')
#5 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->post_data_edit()
#6 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2020-12-29 07:19:45 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'and d.id = a.img_url_id
            WHERE a.id = '4'' at line 4 in C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\Riyadh\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT a.billbo...')
#1 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('SELECT a.billbo...')
#2 C:\xampp\htdocs\Riyadh\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT a.billbo...')
#3 C:\xampp\htdocs\Riyadh\app\Models\User_model.php(411): CodeIgniter\Database\BaseConnection->query('SELECT a.billbo...')
#4 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(231): App\Models\User_model->post_data_edit('4', '1')
#5 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->post_data_edit()
#6 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-12-29 08:57:40 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 244, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(244): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 08:57:42 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 244, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(244): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 08:59:13 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 244, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(244): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 08:59:14 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 244, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(244): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 08:59:14 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 244, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(244): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 08:59:14 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 244, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(244): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 08:59:14 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 244, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(244): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 08:59:15 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 244, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(244): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 08:59:15 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 244, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(244): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 08:59:16 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 244, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(244): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 08:59:16 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 244, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(244): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 08:59:16 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 244, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(244): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 08:59:16 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 244, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(244): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 08:59:17 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 244, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(244): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 08:59:17 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 244, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(244): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 08:59:18 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 244, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(244): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 09:01:40 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 244, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(244): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 09:01:40 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 244, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(244): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 09:01:40 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 244, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(244): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 09:01:41 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 244, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(244): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 09:01:41 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 244, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(244): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 09:01:41 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 244, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(244): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 09:03:46 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 246, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(246): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 09:03:47 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 246, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(246): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 09:03:47 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 246, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(246): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 09:03:47 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 246, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(246): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 09:03:48 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 246, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(246): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 09:03:48 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 246, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(246): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 09:04:59 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 248, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(248): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 09:05:00 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 248, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(248): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 09:05:00 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 248, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(248): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 09:05:01 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 248, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(248): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 09:05:01 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 248, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(248): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 09:05:01 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 248, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(248): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 09:05:02 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 248, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(248): mail('ilyaivanov19951...', 'My subject', 'First line of t...')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 18:40:06 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 240, Array)
#1 C:\xampp\htdocs\Riyadh\app\Controllers\Home.php(240): mail('ilyaivanov19951...', 'test', 'please help me')
#2 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(931): App\Controllers\Home->send_offer()
#3 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\Riyadh\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Riyadh\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-12-29 19:33:20 --> CodeIgniter\Autoloader\Autoloader::main(): Failed opening required 'PHPMailer/Exception.php' (include_path='C:\xampp\php\PEAR')
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
